version: "3"

services:
# Identifie les jobs et ressources avec les noms jobs*ressources,
  namenode:
    image: agileops/hadoop-namenode:2.9.1
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - 50070:50070
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: agileops/hadoop-datanode:2.9.1
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: agileops/hadoop-resourcemanager:2.9.1
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env

# Identifie les machines
  nodemanager1:
    image: agileops/hadoop-nodemanager:2.9.1
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

# Garde l'historique des transations
  historyserver:
    image: agileops/hadoop-historyserver:2.9.1
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

# Gère les query et les index hbase
  hbase:
    image: agileops/hbase-standalone:1.4.4-wip
    hostname: hbase
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 16301:16301
      - 2888:2888
      - 3888:3888
      - 2181:2181
      - 9090:9090
      - 8765:8765
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 namenode:2181"
    env_file:
      - ./hbase-standalone.env
      - ./hadoop.env

# Agileops ;-) Outils de datascience (BigData & ml)
  fastds:
     image: agileops/fastds-tutorial:latest
     # build: .
     volumes:
       - ./data:/work-dir/data
     restart: "no"
     ports:
       - 8888:8888
       - 8088:8088
       - 9000:9000
     environment:
       BIND_ADDRESS: 0.0.0.0

  zoo1:
    image: zookeeper:3.4.12
    hostname: zoo1
    container_name: zoo1
    volumes:
      - zoo1_data:/zookeeper-data

    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
  zoo1_data:
