version: "3"

services:
# Identifie les jobs et ressources avec les noms jobs*ressources,
  namenode:
    image: fastds/hadoop-namenode:2.9.1
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: fastds/hadoop-datanode:2.9.1
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: fastds/hadoop-resourcemanager:2.9.1
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env

# Identifie les machines
  nodemanager1:
    image: fastds/hadoop-nodemanager:2.9.1
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

# Garde l'historique des transations
  historyserver:
    image: fastds/hadoop-historyserver:2.9.1
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env

# Gère les query et les index hbase
  hbase:
    image: fastds/hbase-standalone:2.0.0
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
      - 9090:9090
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hbase-standalone.env

# Fastds ;-) Outils de datascience (BigData & ml)
  fastds:
     image: fastds-tutorial:latest
     # build: .
     volumes:
       - ./data:/work-dir/data
     restart: "no"
     ports:
       - 8888:8888
       - 8088:8088
       - 9000:9000
     environment:
       BIND_ADDRESS: 0.0.0.0

  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "9999:8888"
    #command: ./build/env/bin/hue runserver_plus 0.0.0.0:8888
    command: tail -f /dev/null
    volumes:
      # - ../../../apps/hbase/src:/hue/apps/hbase/src
      - ./hue.ini:/hue/desktop/conf/hue.ini

# # hbase ui
#   hue:
#      image: gethue/hue:latest
#      # build: .
#      ports:
#         - 9999:8888

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
